const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..')
const admin = fs.readFileSync(path.join(root, 'admin', 'web', 'index.html'), 'utf8')
const activityJs = fs.readFileSync(path.join(root, 'pages', 'activities', 'activities.js'), 'utf8')
const activityWxml = fs.readFileSync(path.join(root, 'pages', 'activities', 'activities.wxml'), 'utf8')
const adminCloud = fs.readFileSync(path.join(root, 'cloudfunctions', 'activityAdmin', 'index.js'), 'utf8')

const voiceTab = admin.indexOf('id="aiModeVoiceTab"')
const imageTab = admin.indexOf('id="aiModeImageTab"')
assert(voiceTab >= 0 && voiceTab < imageTab, 'text/voice import is the first option')
assert(admin.includes('id="aiModeVoiceTab" class="active"'), 'text/voice import is active by default')
assert(admin.includes('文字或语音上传'), 'text/voice import uses the requested label')
assert(admin.includes('芯片设计入门讲座'), 'text/voice import includes a complete example')
assert(admin.includes('onclick="aiUseVoiceExample()"'), 'example can be inserted into the input')
assert(admin.includes('AI 修改内容'), 'side assistant is labeled as content modification')
assert(admin.includes("callAdminHttp('aiReviseActivityDraft', payload)"), 'side assistant revises the current draft')

assert(!admin.includes('actPopupContent'), 'admin popup fields are removed')
assert(!activityJs.includes('popupVisible'), 'activity click no longer opens the legacy popup')
assert(!activityWxml.includes('act-popup'), 'legacy popup markup is removed')
assert(adminCloud.includes("popupContentZh: ''"), 'saving an activity clears legacy popup content')
assert(adminCloud.includes('function normalizeAiDraft'), 'AI drafts are normalized before entering the form')
assert(adminCloud.includes('for (let attempt = 0; attempt < 2; attempt++)'), 'text AI retries transient failures once')
assert(adminCloud.includes('return ok({ draft: normalizeAiDraft(draft) })'), 'poster recognition output is normalized')
assert(adminCloud.includes('callDoubaoVision'), 'poster recognition supports Doubao vision')
assert(adminCloud.includes("process.env.ARK_API_KEY"), 'Doubao key is read from environment only')
assert(admin.includes('enabledPublisherKeys'), 'frontend preview filters disabled publishers like the mini program')
assert(admin.includes('for (let attempt = 0; attempt < 2; attempt++)'), 'admin cloud calls retry after anonymous auth refresh')
assert(admin.includes("识别超时，请重试或换一张清晰海报"), 'poster recognition exits instead of hanging forever')
assert(admin.includes("if (!C.httpTriggerUrl) throw new Error('HTTP 触发器未配置')"), 'poster recognition does not call an unconfigured HTTP path')
assert(admin.includes("console.error('活动方主页渲染失败', e)"), 'publisher page render errors are recovered')
assert(admin.includes('(Array.isArray(activityList) ? activityList : []).filter'), 'publisher page tolerates missing activity data')
assert(admin.includes("if (!page.innerHTML.trim())"), 'publisher page switches only after successful rendering')
const workspaceEnd = admin.indexOf('<!-- 预约情况：自研预约概览、报名名单与导出 -->')
assert(workspaceEnd > admin.indexOf('id="publisherPage"'), 'workspace detail page closes before sibling panels')
assert(admin.includes('</div>\n        <!-- 活动方详情页必须与 workspaceHome 同级'),
  'publisher page sits outside the list container')
assert.strictEqual((admin.slice(admin.indexOf('id="publisherPage"'), workspaceEnd).match(/<\/div>/g) || []).length, 2,
  'publisher page and workspace panel close before reservation panel')

assert(admin.includes('wxf6158c254a04cf1b'), 'quick reservation official AppID is preconfigured')
assert(admin.includes('toggleJumpFields(true)'), 'selecting a jump type applies its preset')
assert(admin.includes('value="registrationTool"'), 'registration tool is available as a jump type')
assert(admin.includes('id="actTargetShortLink"'), 'admin accepts copied mini-program links')
assert(admin.includes('#小程序://报名工具/diQKBEbq9vjI7To'), 'registration tool link is preconfigured')
assert(admin.includes('每个活动使用对应的链接'), 'quick reservation explains that each activity needs its own link')
assert(adminCloud.includes('targetShortLink'), 'activity admin persists mini-program links')

assert(admin.includes('#activityModal .modal-body { grid-template-columns: minmax(0, 1fr); }'), 'activity editor collapses to one column on mobile')
assert(admin.includes('class="ai-side-mascot"'), 'mobile AI assistant includes the octopus mascot')
assert(admin.includes("matchMedia('(max-width: 900px)')"), 'mobile AI assistant starts in a compact state')
assert(admin.includes('white-space: nowrap'), 'mobile controls guard against character-by-character wrapping')

console.log('admin-activity-workflow.test.js: all assertions passed')
