/**
 * icsGenerator.js — iCalendar (RFC 5545) 生成器（前端版）
 * Apple Calendar 兼容：FLOATING 时间 + 确定性 UID + SEQUENCE:0 + TRANSP:OPAQUE
 */
var PRODID = '-//Xipoo//Course Schedule//ZH'
function hash(s) { var h = 5381; for (var i = 0; i < s.length; i++) { h = ((h << 5) + h) + s.charCodeAt(i); h = h & h; } return (h >>> 0).toString(16).padStart(8, '0').slice(0, 8) }
function pDate(v) { if (v instanceof Date) return new Date(v.getFullYear(), v.getMonth(), v.getDate()); var s = String(v || '').trim(); if (!s) return null; var d = new Date(s.replace(/\//g, '-') + 'T00:00:00'); return Number.isNaN(d.getTime()) ? null : new Date(d.getFullYear(), d.getMonth(), d.getDate()) }
function addD(d, n) { var r = new Date(d); r.setDate(r.getDate() + n); return r }
function fDt(d) { return '' + d.getFullYear() + String(d.getMonth() + 1).padStart(2, '0') + String(d.getDate()).padStart(2, '0') }
function fTm(t) { var p = String(t || '00:00').split(':'); return String(parseInt(p[0], 10) || 0).padStart(2, '0') + String(parseInt(p[1], 10) || 0).padStart(2, '0') + '00' }
function fSt() { var n = new Date(); return '' + n.getUTCFullYear() + String(n.getUTCMonth() + 1).padStart(2, '0') + String(n.getUTCDate()).padStart(2, '0') + 'T' + String(n.getUTCHours()).padStart(2, '0') + String(n.getUTCMinutes()).padStart(2, '0') + String(n.getUTCSeconds()).padStart(2, '0') + 'Z' }
function esc(v) { return String(v || '').replace(/\\/g, '\\\\').replace(/;/g, '\\;').replace(/,/g, '\\,').replace(/\n/g, '\\n').replace(/\r/g, '') }
function uid(c, idx, ts) { return hash([esc(c.title || 'course'), c.weekday, c.startTime || c.start, c.endTime || c.end, c.weekStart, c.weekEnd, c.weekType || 'all', fDt(ts), idx].join('|')) + '-0@xipoo' }
function rrule(wt, ws, we) { var t = (wt || 'all').toLowerCase(); var s = Number(ws) || 1, e = Number(we) || s; var iv = (t === 'odd' || t === 'even') ? 2 : 1; var ct = iv === 1 ? (e - s + 1) : (Math.floor((e - s) / iv) + 1); return ct <= 1 ? '' : 'FREQ=WEEKLY;INTERVAL=' + iv + ';COUNT=' + ct }
function vevent(c, idx, ts) { var wd = Number(c.weekday) || 1; var ws = Number(c.weekStart) || 1, we = Number(c.weekEnd) || ws; var fd = addD(ts, (ws - 1) * 7 + (wd - 1)); var st = c.startTime || c.start || '09:00'; var et = c.endTime || c.end || '10:00'; var dts = fDt(fd) + 'T' + fTm(st); var dte = fDt(fd) + 'T' + fTm(et); var sum = esc(c.title || '未命名课程'); var loc = esc(c.location || c.place || ''); var rr = rrule(c.weekType, ws, we); var dp = []; if (c.teacher) dp.push('教师: ' + c.teacher); if (c.courseCode) dp.push('课程代码: ' + c.courseCode); var lb = { all: '全周', odd: '单周', even: '双周' }; dp.push('教学周: ' + ws + '-' + we + ' (' + (lb[c.weekType] || '全周') + ')'); dp.push('时间: ' + st + '-' + et + ' (北京时间)'); var a = ['BEGIN:VEVENT', 'DTSTART:' + dts, 'DTEND:' + dte, 'DTSTAMP:' + fSt(), 'UID:' + uid(c, idx, ts), 'SEQUENCE:0', 'TRANSP:OPAQUE', 'SUMMARY:' + sum]; if (loc) a.push('LOCATION:' + loc); if (dp.length) a.push('DESCRIPTION:' + esc(dp.join('\\n'))); if (rr) a.push('RRULE:' + rr); a.push('END:VEVENT'); return a.join('\r\n') }
function generateCourseIcs(courses) { if (!Array.isArray(courses) || !courses.length) throw new Error('课程列表为空'); var ts = null; for (var i = 0; i < courses.length; i++) { ts = pDate(courses[i].termStart); if (ts) break; } if (!ts) { var n = new Date(); ts = new Date(n.getFullYear(), 8, 1); var dow = ts.getDay(); if (dow !== 1) ts.setDate(ts.getDate() + (dow === 0 ? 1 : 8 - dow)); } var hdr = 'BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:' + PRODID + '\r\nCALSCALE:GREGORIAN\r\nMETHOD:PUBLISH\r\nX-WR-CALNAME:Xipoo\r\nX-WR-TIMEZONE:Asia/Shanghai'; var evts = courses.map(function (c, idx) { return vevent(c, idx, pDate(c.termStart) || ts); }); return hdr + '\r\n' + evts.join('\r\n') + '\r\nEND:VCALENDAR\r\n' }
module.exports = { generateCourseIcs: generateCourseIcs }

