const users = [
  {
    id: 'XP1001',
    phone: '13800000001',
    password: '123456',
    name: 'Sien',
    school: 'XJTLU',
    major: 'MSE',
    degree: 'Year 2',
    gender: '男',
    avatar: 'S',
    bio: 'Product and campus life optimizer',
    signature: '把复杂的校园生活安排得简单一点。',
    featureTags: ['产品', '旅行', '羽毛球'],
    profileTheme: 'mint',
    profileVisibility: { gender: false, degree: false, major: false, school: false, tags: false, bio: false },
    buddyWechatId: 'sien_xipoo',
    subscriptions: ['chips', 'badminton', 'campus'],
    grade: '大二',
    selectedTags: ['tag_study_01', 'tag_sport_03', 'tag_meal_01'],
    lastActiveAt: new Date().toISOString()
  },
  {
    id: 'XP1002',
    phone: '13800000002',
    password: '123456',
    name: 'Luoting',
    school: 'XJTLU',
    major: 'MSE',
    degree: 'Year 2',
    gender: '男',
    avatar: 'L',
    bio: 'AI algorithm and backend',
    signature: '代码写清楚，时间留给生活。',
    featureTags: ['算法', '摄影', '桌游'],
    profileTheme: 'sky',
    profileVisibility: { gender: false, degree: false, major: false, school: false, tags: false, bio: false },
    buddyWechatId: 'luoting_ai',
    subscriptions: ['chips', 'badminton', 'campus'],
    grade: '大二',
    selectedTags: ['tag_study_03', 'tag_sport_01', 'tag_ent_01'],
    lastActiveAt: new Date().toISOString()
  },
  {
    id: 'XP1003',
    phone: '13800000003',
    password: '123456',
    name: 'Jingyi',
    school: 'XJTLU',
    major: 'Design',
    degree: 'Year 2',
    gender: '女',
    avatar: 'J',
    bio: 'UI/UX and activity research',
    signature: '在校园里收集好设计和好天气。',
    featureTags: ['设计', '展览', '咖啡'],
    profileTheme: 'coral',
    profileVisibility: { gender: false, degree: false, major: false, school: false, tags: false, bio: false },
    buddyWechatId: 'jingyi_design',
    subscriptions: ['chips', 'badminton', 'campus'],
    grade: '大二',
    selectedTags: ['tag_study_01', 'tag_meal_03', 'tag_ent_02'],
    lastActiveAt: new Date().toISOString()
  }
]

const schedules = {
  XP1001: [{
    id: 'course-xp1001-cct007',
    title: 'CCT007 Data Structures',
    courseCode: 'CCT007', courseId: 'CCT007_T01',
    section: 'T01',
    term: '2025-26-S2',
    date: '2026-06-16',
    weekday: 2,
    start: '15:00',
    end: '16:00',
    place: 'CCT G15',
    teacher: 'Dr. Chen',
    type: 'Course',
    confirmed: true
  }, {
    id: 'course-xp1001-ent103-s2',
    title: 'ENT103 Entrepreneurship',
    courseCode: 'ENT103', courseId: 'ENT103_S2',
    section: 'SESSION 2',
    term: '2025-26-S2',
    date: '2026-06-16',
    weekday: 2,
    start: '15:00',
    end: '16:00',
    place: 'EB 203',
    teacher: 'Dr. Li',
    type: 'Course',
    confirmed: true
  }],
  XP1002: [{
    id: 'course-xp1002-cct007',
    title: 'CCT007 Data Structures',
    courseCode: 'CCT007', courseId: 'CCT007_T01',
    section: 'T01',
    term: '2025-26-S2',
    date: '2026-06-16',
    weekday: 2,
    start: '15:00',
    end: '16:00',
    place: 'CCT G15',
    teacher: 'Dr. Chen',
    type: 'Course',
    confirmed: true
  }, {
    id: 'course-xp1002-ent103-s1',
    title: 'ENT103 Entrepreneurship',
    courseCode: 'ENT103', courseId: 'ENT103_S1',
    section: 'SESSION 1',
    term: '2025-26-S2',
    date: '2026-06-15',
    weekday: 1,
    start: '10:00',
    end: '11:00',
    place: 'EB 201',
    teacher: 'Dr. Li',
    type: 'Course',
    confirmed: true
  }],
  XP1003: [{
    id: 'course-xp1003-cct007',
    title: 'CCT007 Data Structures',
    courseCode: 'CCT007', courseId: 'CCT007_T01',
    section: 'T01',
    term: '2025-26-S2',
    date: '2026-06-16',
    weekday: 2,
    start: '15:00',
    end: '16:00',
    place: 'CCT G15',
    teacher: 'Dr. Chen',
    type: 'Course',
    confirmed: true
  }, {
    id: 'course-xp1003-ent104-s1',
    title: 'ENT104 Venture Practice',
    courseCode: 'ENT104', courseId: 'ENT104_S1',
    section: 'SESSION 1',
    term: '2025-26-S2',
    date: '2026-06-18',
    weekday: 4,
    start: '14:00',
    end: '15:00',
    place: 'EB 205',
    teacher: 'Dr. Wang',
    type: 'Course',
    confirmed: true
  }]
}

const activitySchedules = {
  XP1001: [],
  XP1002: [],
  XP1003: []
}

const friendships = [
  {
    id: 'friendship-xp1001-xp1002',
    users: ['XP1001', 'XP1002'],
    share: { XP1001: true, XP1002: true },
    createdAt: '2026-06-01T08:00:00.000Z'
  },
  {
    id: 'friendship-xp1001-xp1003',
    users: ['XP1001', 'XP1003'],
    share: { XP1001: true, XP1003: true },
    createdAt: '2026-06-01T08:05:00.000Z'
  },
  {
    id: 'friendship-xp1002-xp1003',
    users: ['XP1002', 'XP1003'],
    share: { XP1002: true, XP1003: true },
    createdAt: '2026-06-01T08:10:00.000Z'
  }
]

const friendRequests = []

const buddyOptIns = [
  {
    id: 'buddy-optin-xp1002-cct007',
    userId: 'XP1002',
    courseId: 'course-xp1002-cct007',
    enabled: true,
    tags: ['作业', '项目组队'],
    availabilityStart: '16:00',
    availabilityEnd: '18:00',
    buddyWechatId: 'luoting_ai',
    bio: '希望一起梳理算法题和课程项目。',
    consent: true,
    createdAt: '2026-06-01T08:00:00.000Z',
    updatedAt: '2026-06-01T08:00:00.000Z'
  },
  {
    id: 'buddy-optin-xp1003-cct007',
    userId: 'XP1003',
    courseId: 'course-xp1003-cct007',
    enabled: true,
    tags: ['复习', '考试'],
    availabilityStart: '14:00',
    availabilityEnd: '17:00',
    buddyWechatId: 'jingyi_design',
    bio: '想找固定课搭子，每周课后复盘。',
    consent: true,
    createdAt: '2026-06-01T08:10:00.000Z',
    updatedAt: '2026-06-01T08:10:00.000Z'
  }
]

const courseTeams = []
const courseTeamApplications = []
const courseTeamMembers = []
const userBlocks = []
const userReports = []
const riskEvents = []
const scheduleMatches = []
const buddyPosts = []
const buddyApplications = []
const buddyMembers = []
const buddyLocationTags = [
  '中央食堂',
  '北区食堂',
  '图书馆',
  '体育馆',
  '操场',
  '创新工场',
  '教学楼公共区'
]

const publishers = [
  {
    key: 'chips',
    name: 'School of CHIPS',
    nameZh: '芯片学院',
    accent: '#65e882',
    verified: true,
    logoUrl: '',
    coverUrl: '/assets/demo-activities/salon-optimized.jpg',
    taglineZh: '让芯片、产业与校园里的年轻想法彼此连接',
    tagline: 'Connecting chips, industry and young ideas on campus',
    locationZh: '西交利物浦大学太仓校区',
    location: 'XJTLU Taicang Campus',
    foundedLabelZh: '学院官方活动方',
    foundedLabel: 'Official school organizer',
    storyTitleZh: '从课堂之外，看见芯片产业',
    storyTitle: 'See the chip industry beyond the classroom',
    storyZh: '我们持续策划学术沙龙、产业交流、科研展示与轻社交活动，让同学更早接触真实行业，也让校园里的好项目被更多人看见。',
    story: 'We curate salons, industry exchanges, research showcases and social events that connect students with the real semiconductor world.',
    contentTagsZh: ['半导体', '产业交流', '科研展示', '学生社区'],
    contentTags: ['Semiconductor', 'Industry', 'Research', 'Community'],
    contactLabelZh: '联系学院活动团队',
    contactLabel: 'Contact the events team',
    contactValue: '',
    galleryUrls: [
      '/assets/demo-activities/salon-optimized.jpg',
      '/assets/demo-activities/poster-exhibition.jpg',
      '/assets/demo-activities/pingpong.jpg'
    ],
    campus: 'tc',
    discoveryTags: ['college'],
    descriptionZh: '学术沙龙、竞赛、产业交流与学院活动',
    description: 'Academic salons, competitions and industry events'
  },
  {
    key: 'badminton',
    name: 'Badminton Club',
    nameZh: '羽毛球社',
    accent: '#42b96f',
    verified: true,
    discoveryTags: ['sip', 'tc'],
    descriptionZh: '校队训练、友谊赛与新手体验活动',
    description: 'Training sessions, friendly matches and beginner events'
  },
  {
    key: 'xec',
    name: 'XEC Sports Centre',
    nameZh: '西浦创业家学院体育中心',
    accent: '#5ee7bb',
    verified: true,
    discoveryTags: ['sip', 'tc'],
    descriptionZh: '运动赛事、体验课与校园健康活动',
    description: 'Sports, trial classes and campus wellness'
  },
  {
    key: 'campus',
    name: 'Campus Events',
    nameZh: '校园活动组',
    accent: '#b9a6ff',
    verified: true,
    discoveryTags: ['sip', 'immersion'],
    descriptionZh: '市集、展览、讲座与跨学院公共活动',
    description: 'Markets, exhibitions and campus-wide events'
  },
  {
    key: 'library',
    name: 'XJTLU Library',
    nameZh: '西浦图书馆',
    accent: '#ffb65c',
    verified: true,
    discoveryTags: ['sip', 'immersion'],
    descriptionZh: '阅读、信息素养、数据库培训与自习活动',
    description: 'Reading, research skills and study events'
  },
  {
    key: 'career',
    name: 'Career Centre',
    nameZh: '西浦就业发展中心',
    accent: '#f27c96',
    verified: true,
    discoveryTags: ['sip', 'college'],
    descriptionZh: '招聘、职业工作坊与企业开放日',
    description: 'Careers, recruitment and employer events'
  },
  {
    key: 'pai_space',
    name: 'PAI Space',
    nameZh: 'PAI空间',
    accent: '#a78bfa',
    verified: false,
    logoUrl: '/assets/publishers/paispace-logo.png',
    coverUrl: '/assets/publishers/paispace-cover.jpg',
    taglineZh: '在 AI 的浪潮里，把每一个奇思妙想变成看得见的作品',
    tagline: 'Ride the AI wave — turn every spark of an idea into something real',
    locationZh: 'PAI空间 · 苏州校区图书馆大楼',
    location: 'PAI Space, Library Building, Suzhou Campus',
    foundedLabelZh: '人工智能创新社区',
    foundedLabel: 'AI innovation community',
    storyTitleZh: '让 AI 从课堂走进每一个灵感现场',
    storyTitle: 'Bringing AI from the classroom to every spark of inspiration',
    storyZh: 'PAI空间是面向全校师生的人工智能创新社区：机器学习工作坊、AI 应用黑客松、论文共读会与前沿技术沙龙……我们相信，AI 不只是少数人的专业，而是每个人都能上手的新工具。在这里，一个想法从白板到 Demo，往往只需要一个晚上。',
    story: 'PAI Space is an AI innovation community open to the whole campus: machine-learning workshops, AI hackathons, paper reading sessions and frontier tech salons. We believe AI is not the privilege of a few majors, but a new tool everyone can pick up. Here, an idea often travels from whiteboard to demo in a single evening.',
    contentTagsZh: ['AI工作坊', '黑客松', '论文共读', '技术沙龙'],
    contentTags: ['AI Workshops', 'Hackathon', 'Paper Reading', 'Tech Salon'],
    contactLabelZh: '联系 PAI空间小助手',
    contactLabel: 'Contact PAI Space',
    contactValue: 'pai-space@xjtlu.edu.cn',
    galleryUrls: [
      '/assets/demo-activities/pingpong.jpg',
      '/assets/demo-activities/poster-exhibition.jpg',
      '/assets/demo-activities/salon-optimized.jpg'
    ],
    discoveryTags: ['immersion', 'college'],
    descriptionZh: 'AI工作坊、黑客松、论文共读与前沿技术沙龙',
    description: 'AI workshops, hackathons, paper reading sessions and frontier tech salons'
  },
  {
    key: 'fun_workshop',
    name: 'Fun Workshop',
    nameZh: 'Fun Workshop',
    accent: '#17948a',
    verified: false,
    logoUrl: '/assets/publishers/funworkshop-logo.png',
    coverUrl: '/assets/publishers/funworkshop-cover.jpg',
    taglineZh: '这个夏天，一起开发、探索、讨论，发出我们的声音',
    tagline: 'Explore, develop, discuss — make our voice',
    locationZh: 'Cozy Coffee · 太仓校区 E 栋一楼',
    location: 'Cozy Coffee, Ground floor, Building E, Taicang Campus',
    foundedLabelZh: 'XJTLU PGR 非官方指导社区',
    foundedLabel: 'Unofficial guidance for XJTLU PGR students',
    storyTitleZh: 'Claw Twin Initiative：让 AI 分身替我们干活',
    storyTitle: 'Claw Twin Initiative: agents that work on our behalf',
    storyZh: 'Fun Workshop 是一个围绕 AI 智能体（Claw Twin）的开放工作坊社区：AI 分身可以替我们处理琐事，但当它们遇到别人家的智能体、被带偏、说错话做错事时怎么办？这个夏天，我们每周一次相聚 Cozy Coffee，一起开发、探索、讨论，发出我们的声音。欢迎任何人参加，我们也提供入门指导服务。',
    story: 'Fun Workshop is an open workshop community around AI agents (Claw Twin): agents can work on our behalf, but what happens when they meet agents from others and get misled? This summer we meet weekly at Cozy Coffee to explore, develop and discuss. Everyone is welcome — entry-level guidance provided.',
    contentTagsZh: ['AI智能体', '开发', '探索', '讨论'],
    contentTags: ['AI Agents', 'Develop', 'Explore', 'Discuss'],
    contactLabelZh: '联系 Fun Workshop',
    contactLabel: 'Contact Fun Workshop',
    contactValue: '',
    galleryUrls: [
      '/assets/demo-activities/salon-optimized.jpg',
      '/assets/demo-activities/poster-exhibition.jpg'
    ],
    discoveryTags: ['tc', 'immersion'],
    descriptionZh: 'AI 智能体主题周常工作坊，欢迎零基础参加',
    description: 'Weekly AI-agent workshops, beginner friendly'
  }
]

// 活动分类（模块 4）：scope=paispace 为 π空间专属二级分类，global 为全站通用
const activityCategories = [
  { scope: 'paispace', key: 'taiji', nameZh: '太极拳', nameEn: 'Tai Chi', sort: 1, enabled: true },
  { scope: 'paispace', key: 'boardgame', nameZh: '桌游', nameEn: 'Board Games', sort: 2, enabled: true },
  { scope: 'paispace', key: 'startup', nameZh: '创业分享', nameEn: 'Startup Sharing', sort: 3, enabled: true },
  { scope: 'paispace', key: 'salon', nameZh: '讲座沙龙', nameEn: 'Talks & Salons', sort: 4, enabled: true },
  { scope: 'paispace', key: 'venue', nameZh: '场地预约', nameEn: 'Venue Booking', sort: 5, enabled: true },
  { scope: 'global', key: 'lecture', nameZh: '讲座', nameEn: 'Lecture', sort: 1, enabled: true },
  { scope: 'global', key: 'exhibition', nameZh: '展览', nameEn: 'Exhibition', sort: 2, enabled: true }
]

const activityRegistrations = {
  XP1001: [],
  XP1002: [],
  XP1003: []
}

const activities = [
  {
    id: 'activity-pingpong',
    publisherKey: 'chips',
    category: 'college',
    typeZh: '学院活动',
    typeEn: 'College Event',
    title: 'Ping-Pong Fun Day',
    titleZh: '芯动西浦趣味乒乓球比赛',
    cover: "url('/assets/demo-activities/pingpong.jpg') center/cover no-repeat",
    coverUrl: '/assets/demo-activities/pingpong.jpg',
    time: 'May 20, 17:30-19:30',
    date: '2025-05-20',
    start: '17:30',
    end: '19:30',
    place: 'XEC Sports Centre Table Tennis Room',
    placeZh: '西浦创业家学院体育中心乒乓球馆',
    host: 'School of CHIPS & XEC Sports Centre',
    hostZh: '芯片学院联合西浦创业家学院体育中心',
    desc: 'A playful evening tournament designed for light competition, fun challenges, and social interaction across the whole campus.',
    descZh: '面向全校师生的轻竞技趣味乒乓球活动，主打轻松上阵、趣味挑战和社交互动。',
    tags: ['Ping-Pong', 'Sports', 'Social'],
    tagsZh: ['乒乓球', '体育', '社交'],
    scheduleTag: '2025-05-20 17:30-19:30 芯片学院趣味乒乓',
    pinned: true,
    polished: true,
    joined: false,
    liked: false,
    saved: false,
    shareCount: 18,
    likeCount: 230,
    joinCount: 42,
    comments: [
      {
        id: 'comment-pingpong-1',
        name: 'Jingyi',
        text: '海报很有活力，适合和朋友一起去。'
      }
    ]
  },
  {
    id: 'activity-salon',
    publisherKey: 'chips',
    category: 'college',
    typeZh: '学术沙龙',
    typeEn: 'Academic Salon',
    title: 'CHIPS Academic Salon',
    titleZh: '“芯”动西浦，智创未来思享会',
    cover: "url('/assets/demo-activities/salon-optimized.jpg') center/cover no-repeat",
    coverUrl: '/assets/demo-activities/salon-optimized.jpg',
    time: 'Nov 12, 13:30-17:00',
    date: '2025-11-12',
    start: '13:30',
    end: '17:00',
    place: 'XJTLU Taicang Campus G-1006',
    placeZh: '西交利物浦大学太仓校区 G-1006',
    host: 'School of CHIPS',
    hostZh: '西交利物浦大学芯片学院',
    desc: 'An academic salon focused on semiconductor industry, external mentors, and future-facing dialogue between education and industry.',
    descZh: '聚焦半导体产业、校外导师与产教融合的一场学术沙龙和行业思享会。',
    tags: ['Salon', 'Semiconductor', 'Mentor'],
    tagsZh: ['沙龙', '半导体', '导师'],
    scheduleTag: '2025-11-12 13:30-17:00 CHIPS Academic Salon',
    pinned: false,
    polished: false,
    joined: false,
    liked: false,
    saved: false,
    shareCount: 9,
    likeCount: 168,
    joinCount: 25,
    comments: [
      {
        id: 'comment-salon-1',
        name: 'Sien',
        text: '这个活动信息量很足，详情页适合展开看。'
      }
    ]
  },
  {
    id: 'activity-exhibition',
    publisherKey: 'chips',
    category: 'college',
    typeZh: '海报展',
    typeEn: 'Poster Exhibition',
    title: 'Winter Research Poster Exhibition',
    titleZh: '冬季项目研究海报展',
    cover: "url('/assets/demo-activities/poster-exhibition.jpg') center/cover no-repeat",
    coverUrl: '/assets/demo-activities/poster-exhibition.jpg',
    time: 'Apr 15, 15:00-17:00',
    date: '2025-04-15',
    start: '15:00',
    end: '17:00',
    place: 'Taicang Campus GA2001',
    placeZh: '太仓校区 GA2001',
    host: 'School of CHIPS AY2526',
    hostZh: 'AY2526 芯片学院',
    desc: 'A poster exhibition featuring winter research projects, master industrial research work, and dissertation showcases.',
    descZh: '展示冬季研究项目、硕士产业研究和毕业论文成果的一场海报展。',
    tags: ['Poster', 'Research', 'Exhibition'],
    tagsZh: ['海报', '科研', '展览'],
    scheduleTag: '2025-04-15 15:00-17:00 Winter Research Poster Exhibition',
    pinned: false,
    polished: true,
    joined: false,
    liked: false,
    saved: false,
    shareCount: 11,
    likeCount: 142,
    joinCount: 19,
    comments: [
      {
        id: 'comment-exhibition-1',
        name: 'Luoting',
        text: '纵向海报很适合做成活动详情卡。'
      }
    ]
  },
  {
    id: 'activity-chips-project-day',
    publisherKey: 'chips',
    category: 'college',
    typeZh: '项目展示',
    typeEn: 'Project Showcase',
    title: 'CHIPS Project Demo Day',
    titleZh: '芯片学院项目成果开放日',
    coverUrl: '/assets/demo-activities/poster-exhibition.jpg',
    time: 'Jun 16, 14:00-17:00',
    date: '2026-06-16',
    start: '14:00',
    end: '17:00',
    place: 'Taicang Campus G-1006',
    placeZh: '太仓校区 G-1006',
    host: 'School of CHIPS',
    hostZh: '西浦芯片学院',
    desc: 'Course projects, research prototypes and student team demonstrations.',
    descZh: '集中展示课程项目、科研原型与学生团队成果，并开放现场交流。',
    tagsZh: ['项目', '展示', '芯片'],
    pinned: true,
    likeCount: 156,
    shareCount: 21,
    joinCount: 39,
    comments: []
  },
  {
    id: 'activity-sports-night',
    publisherKey: 'xec',
    category: 'club',
    typeZh: '运动体验',
    typeEn: 'Sports Session',
    title: 'Campus Sports Night',
    titleZh: '校园运动体验夜',
    coverUrl: '/assets/demo-activities/pingpong.jpg',
    time: 'Jun 18, 18:30-20:30',
    date: '2026-06-18',
    start: '18:30',
    end: '20:30',
    place: 'XEC Sports Centre',
    placeZh: '西浦创业家学院体育中心',
    host: 'XEC Sports Centre',
    hostZh: '西浦创业家学院体育中心',
    desc: 'Try badminton, table tennis and functional training in one evening.',
    descZh: '一晚体验羽毛球、乒乓球和体能训练，适合零基础同学参加。',
    tagsZh: ['运动', '体验课', '社交'],
    likeCount: 86,
    shareCount: 12,
    joinCount: 31,
    comments: []
  },
  {
    id: 'activity-campus-market',
    publisherKey: 'campus',
    category: 'club',
    typeZh: '校园市集',
    typeEn: 'Campus Market',
    title: 'Summer Campus Market',
    titleZh: '夏日校园创意市集',
    coverUrl: '/assets/demo-activities/poster-exhibition.jpg',
    time: 'Jun 21, 14:00-19:00',
    date: '2026-06-21',
    start: '14:00',
    end: '19:00',
    place: 'Taicang Campus Central Plaza',
    placeZh: '太仓校区中央广场',
    host: 'Campus Events',
    hostZh: '校园活动组',
    desc: 'Student stalls, music, creative work and community projects.',
    descZh: '学生摊位、音乐表演、创意作品和校园公益项目集中展示。',
    tagsZh: ['市集', '创意', '社团'],
    likeCount: 194,
    shareCount: 35,
    joinCount: 64,
    comments: []
  },
  {
    id: 'activity-library-research',
    publisherKey: 'library',
    category: 'college',
    typeZh: '技能工作坊',
    typeEn: 'Skills Workshop',
    title: 'Research Database Workshop',
    titleZh: '科研数据库高效检索工作坊',
    coverUrl: '/assets/demo-activities/salon-optimized.jpg',
    time: 'Jun 24, 15:00-16:30',
    date: '2026-06-24',
    start: '15:00',
    end: '16:30',
    place: 'Library 3F Training Room',
    placeZh: '图书馆三楼培训室',
    host: 'XJTLU Library',
    hostZh: '西浦图书馆',
    desc: 'Build a repeatable search strategy for assignments and research projects.',
    descZh: '面向课程作业和科研项目，建立可复用的文献检索与管理方法。',
    tagsZh: ['科研', '数据库', '工作坊'],
    likeCount: 73,
    shareCount: 8,
    joinCount: 22,
    comments: []
  },
  {
    id: 'activity-career-open-day',
    publisherKey: 'career',
    category: 'merchant',
    typeZh: '职业发展',
    typeEn: 'Career Event',
    title: 'Technology Employer Open Day',
    titleZh: '科技企业校园开放日',
    coverUrl: '/assets/demo-activities/salon-optimized.jpg',
    time: 'Jul 3, 13:30-17:00',
    date: '2026-07-03',
    start: '13:30',
    end: '17:00',
    place: 'Taicang Campus G Building',
    placeZh: '太仓校区 G 楼',
    host: 'Career Centre',
    hostZh: '西浦就业发展中心',
    desc: 'Meet employers, review roles and join small-group career conversations.',
    descZh: '与企业招聘团队面对面交流，了解岗位并参与小组职业咨询。',
    tagsZh: ['招聘', '科技', '职业'],
    likeCount: 121,
    shareCount: 27,
    joinCount: 48,
    comments: []
  },
  {
    id: 'activity-music-festival',
    publisherKey: 'campus',
    category: 'other',
    typeZh: '校园节庆',
    typeEn: 'Campus Festival',
    title: 'Summer Music Festival',
    titleZh: '音乐节',
    coverUrl: '/assets/demo-activities/poster-exhibition.jpg',
    time: 'Jul 1, 18:00-21:00',
    date: '2026-07-01',
    start: '18:00',
    end: '21:00',
    place: 'Central Lawn',
    placeZh: '中央草坪',
    host: 'Campus Events',
    hostZh: '校园活动组',
    desc: 'An open-air music night with student bands, food stalls and campus community.',
    descZh: '露天音乐之夜，学生乐队演出、美食摊位与校园社交。',
    tagsZh: ['趣味', '音乐', '社交'],
    tagsEn: ['Fun', 'Music', 'Social'],
    scheduleTag: '2026-07-01 18:00-21:00 校园音乐节',
    likeCount: 312,
    shareCount: 56,
    joinCount: 128,
    comments: []
  },
  {
    id: 'activity-badminton-open',
    publisherKey: 'badminton',
    category: 'club',
    typeZh: '社团活动',
    typeEn: 'Club Event',
    title: 'Badminton Open Day',
    titleZh: '羽毛球社开放体验日',
    coverUrl: '/assets/demo-activities/pingpong.jpg',
    time: 'Jul 5, 19:00-21:00',
    date: '2026-07-05',
    start: '19:00',
    end: '21:00',
    place: 'Gymnasium Court 2',
    placeZh: '体育馆二号场地',
    host: 'Badminton Club',
    hostZh: '羽毛球社',
    desc: 'Try badminton with club members, no experience required.',
    descZh: '与社团成员一起体验羽毛球，零基础也可参加。',
    tagsZh: ['羽毛球', '体育', '社团'],
    likeCount: 89,
    shareCount: 14,
    joinCount: 36,
    comments: []
  },
  {
    id: 'activity-paispace-ml-workshop',
    publisherKey: 'pai_space',
    category: 'college',
    typeZh: '技能工作坊',
    typeEn: 'Skills Workshop',
    title: 'AI Workshop: Introduction to Machine Learning',
    titleZh: 'AI工作坊：机器学习入门',
    coverUrl: '/assets/demo-activities/salon-optimized.jpg',
    time: 'Jul 30, 15:00-17:00',
    date: '2026-07-30',
    start: '15:00',
    end: '17:00',
    place: 'PAI Space, Library Building',
    placeZh: 'PAI空间 · 苏州校区图书馆大楼',
    host: 'PAI Space',
    hostZh: 'PAI空间',
    desc: 'A hands-on introduction to machine learning: from core concepts to training your first model, no prior experience required.',
    descZh: '零基础友好的机器学习入门工作坊：从核心概念讲起，现场动手训练你的第一个模型，并带走一份可复用的学习路线。',
    tags: ['AI', 'Machine Learning', 'Workshop'],
    tagsZh: ['人工智能', '机器学习', '工作坊'],
    scheduleTag: '2026-07-30 15:00-17:00 AI工作坊：机器学习入门',
    categoryKey: 'salon',
    pinned: true,
    polished: true,
    joined: false,
    liked: false,
    saved: false,
    shareCount: 12,
    likeCount: 96,
    joinCount: 28,
    comments: []
  },
  {
    id: 'activity-paispace-boardgame-night',
    publisherKey: 'pai_space',
    category: 'club',
    typeZh: '社交活动',
    typeEn: 'Social Event',
    title: 'PAI Space Board Game Night',
    titleZh: 'π空间桌游之夜',
    coverUrl: '/assets/demo-activities/pingpong.jpg',
    time: 'Aug 6, 19:00-21:00',
    date: '2026-08-06',
    start: '19:00',
    end: '21:00',
    place: 'PAI Space, Library Building',
    placeZh: 'PAI空间 · 苏州校区图书馆大楼',
    host: 'PAI空间主理人',
    hostZh: 'PAI空间主理人',
    desc: 'A casual evening of board games at PAI Space — bring a friend or make new ones.',
    descZh: '在 π空间来一场轻松的桌游之夜：阿瓦隆、UNO、剧本杀轮番上桌，带朋友来或现场认识新朋友。',
    tags: ['Board Games', 'Social'],
    tagsZh: ['桌游', '社交'],
    scheduleTag: '2026-08-06 19:00-21:00 π空间桌游之夜',
    categoryKey: 'boardgame',
    pinned: false,
    polished: false,
    joined: false,
    liked: false,
    saved: false,
    shareCount: 0,
    likeCount: 0,
    joinCount: 0,
    comments: []
  },
  {
    id: 'activity-funworkshop-claw-twin-20260723',
    publisherKey: 'fun_workshop',
    category: 'club',
    typeZh: '工作坊',
    typeEn: 'Workshop',
    title: 'Claw Twin Initiative Workshop',
    titleZh: 'Claw Twin Initiative 工作坊',
    coverUrl: '/assets/publishers/funworkshop-cover.jpg',
    time: 'Jul 23, 14:00-16:00',
    date: '2026-07-23',
    start: '14:00',
    end: '16:00',
    place: 'Cozy Coffee, Ground floor, Building E, Taicang Campus',
    placeZh: 'Cozy Coffee · 太仓校区 E 栋一楼',
    host: 'Fun Workshop',
    hostZh: 'Fun Workshop',
    desc: 'Weekly AI-agent workshop: explore, develop and discuss how agents work on our behalf. Beginner friendly, everyone welcome.',
    descZh: '每周一次的 AI 智能体主题工作坊：一起开发、探索、讨论 AI 分身如何替我们干活，以及它们被"带坏"时该怎么办。欢迎任何人参加，提供入门指导。',
    tags: ['AI Agents', 'Workshop', 'Community'],
    tagsZh: ['AI智能体', '工作坊', '社区'],
    scheduleTag: '2026-07-23 14:00-16:00 Claw Twin Initiative 工作坊',
    pinned: false,
    polished: true,
    joined: false,
    liked: false,
    saved: false,
    shareCount: 0,
    likeCount: 0,
    joinCount: 0,
    comments: []
  }
]

const matchPool = [
  { userId: 'XP1001', pools: {
    course: { enabled: true, genderFilter: 'any', selectedTags: ['tag_study_01', 'tag_study_03'] },
    study: { enabled: true, genderFilter: 'any', selectedTags: ['tag_study_01', 'tag_study_04'] },
    meal: { enabled: true, genderFilter: 'any', selectedTags: ['tag_meal_01', 'tag_meal_03'] },
    sport: { enabled: true, genderFilter: 'any', selectedTags: ['tag_sport_01', 'tag_sport_03'] },
    selfstudy: { enabled: true, genderFilter: 'any', selectedTags: ['tag_life_01', 'tag_study_01'] },
    entertainment: { enabled: true, genderFilter: 'any', selectedTags: ['tag_ent_01', 'tag_ent_02'] }
  }},
  { userId: 'XP1002', pools: {
    course: { enabled: true, genderFilter: 'any', selectedTags: ['tag_study_03', 'tag_study_05'] },
    study: { enabled: true, genderFilter: 'any', selectedTags: ['tag_study_03', 'tag_sport_01'] },
    meal: { enabled: true, genderFilter: 'any', selectedTags: ['tag_meal_01', 'tag_meal_05'] },
    sport: { enabled: true, genderFilter: 'any', selectedTags: ['tag_sport_01', 'tag_sport_05'] },
    selfstudy: { enabled: true, genderFilter: 'any', selectedTags: ['tag_life_02', 'tag_study_03'] },
    entertainment: { enabled: true, genderFilter: 'any', selectedTags: ['tag_ent_01', 'tag_ent_04'] }
  }},
  { userId: 'XP1003', pools: {
    course: { enabled: true, genderFilter: 'any', selectedTags: ['tag_study_01', 'tag_study_04'] },
    study: { enabled: true, genderFilter: 'any', selectedTags: ['tag_study_01', 'tag_ent_02'] },
    meal: { enabled: true, genderFilter: 'any', selectedTags: ['tag_meal_03', 'tag_meal_04'] },
    sport: { enabled: true, genderFilter: 'any', selectedTags: ['tag_sport_03', 'tag_sport_04'] },
    selfstudy: { enabled: true, genderFilter: 'any', selectedTags: ['tag_life_01', 'tag_life_03'] },
    entertainment: { enabled: true, genderFilter: 'any', selectedTags: ['tag_ent_02', 'tag_ent_03'] }
  }}
]

const matchRequests = []
const matchedPairs = []

module.exports = {
  users,
  schedules,
  activitySchedules,
  friendships,
  friendRequests,
  buddyOptIns,
  courseTeams,
  courseTeamApplications,
  courseTeamMembers,
  userBlocks,
  userReports,
  riskEvents,
  scheduleMatches,
  buddyPosts,
  buddyApplications,
  buddyMembers,
  buddyLocationTags,
  activityCategories,
  publishers,
  activityRegistrations,
  activities,
  matchPool,
  matchRequests,
  matchedPairs
}
